---
# tasks file for cpm prerequisities - not used for cpm

- name: Pre Install Block
  block:

    - name: run CPM pre requisites
      win_shell: |
        $ErrorActionPreference = "SilentlyContinue"
        $Action = .\CPM_PreInstallation.ps1
        $Action | Out-File -FilePath "{{ cpm_prerequisites_log }}"
        $Result = Get-Content "{{ cpm_prerequisites_log }}" | ConvertFrom-Json
        if ($Result.isSucceeded -eq 2) {
            exit 1
        } else {
            exit 0
        }
      args:
        chdir: "{{ cpm_installationautomation_folder }}"

  rescue:

    - name: Get log path for prerequisites
      win_shell: |
        $Result = Get-Content "{{ cpm_prerequisites_log }}"
        Write-Output $Result
      register: log_result

    - fetch:
        src: '{{ item.logPath }}'
        dest: '{{ playbook_dir }}/logs/cpm/{{ inventory_hostname }}_prerequisites.log'
        flat: yes
      with_items:
        - "{{ log_result.stdout | from_json }}"

    - fail:
        msg: 'ERROR: Pre Prerequisites failed. For more info check {{ playbook_dir }}/logs/cpm/{{ inventory_hostname }}_prerequisites.log'
